### ISSUE TITLE
"enable php modules" fails

### ISSUE THREAD

**Issue by ltarasiewicz** [infOpen/ansible-role-php#1]
Hi,

Thanks for this great role.
The thing I noticed is that it fails on "enable php modules". Specifically due to this:

https://github.com/infOpen/ansible-role-php/blob/master/tasks/main.yml#L36-L37

    args  :
      creates : "{{ item.link }}"

I'm wondering what's the purpose of these two lines?

**Comment by achaussier** [comment]
Hello,
Thanks.

These tasks (enable/disable modules) are used to managed additionnal config files installed by system packages.

Example :
infopen@server04:~$ ls /etc/php5/mods-available/
mcrypt.ini
infopen@server04:~$ ls /etc/php5/cli/conf.d/
20-mcrypt.ini

# Vars
php_module_to_enable :
  - name : "mcrypt"
    link : "/etc/php5/cli/conf.d/20-mcrypt.ini"

But I think this should be manage with another method, I will take time today to think about it
If you have some ideas, don't hesitate to share it, you're welcome :)

**Comment by achaussier** [comment]
Some ideas :
 - add config to clean additionnal configuration dirs and have a clean installation of php
 - Manage php plugins to separate roles, with dependencies
 - Add "real" plugins management into this role

**Comment by achaussier** [comment]
Hello,

This took some time, but I updated this role, with many (breaking) changes in config management. It follows the KISS pattern now :)

I've adopted a new modules management, so this problem is resolved.

Alexandre
